//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinhYeuCau
    {
        public string MaCHYC { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string GPU { get; set; }
        public string Storage { get; set; }
        public string OS { get; set; }
        public string DirectX { get; set; }
        public System.Guid MaSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
