//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDKey
    {
        public System.Guid MaHD { get; set; }
        public System.Guid MaSP { get; set; }
        public string CDKey1 { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
