//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.CauHinhKhuyenNghis = new HashSet<CauHinhKhuyenNghi>();
            this.CauHinhYeuCaus = new HashSet<CauHinhYeuCau>();
            this.CDKeys = new HashSet<CDKey>();
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
    
        public System.Guid MaSP { get; set; }
        public string TenSP { get; set; }
        public double Gia { get; set; }
        public DateTime NgayTao { get; set; }
        public DateTime NgayChinhSua { get; set; }
        public string Anh { get; set; }
        public string NoiDung { get; set; }
        public System.Guid MaLSP { get; set; }
        public System.Guid MaNPT { get; set; }
        public System.Guid MaTL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhKhuyenNghi> CauHinhKhuyenNghis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhYeuCau> CauHinhYeuCaus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CDKey> CDKeys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaPhatTrien NhaPhatTrien { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
